server:
  port: 8082

spring:
  application:
    name: dit-admin-service

  cloud:
    nacos:
      discovery:
        server-addr: localhost:20001
        username: nacos
        password: nacos
        namespace: 60a9e1d6-a938-4cb7-966c-5e8482ae5612
      config:
        username: nacos
        password: nacos
        server-addr: localhost:20001
        namespace: 60a9e1d6-a938-4cb7-966c-5e8482ae5612

  config:
    import: nacos:dit-auth.yaml



