server:
  port: 8082

spring:
  application:
    name: dit-system-service
  data:
    redis:
      host: localhost
      port: 16379
      password: 123456  # 如果没有密码可省略
      timeout: 5000

  datasource:
    url: jdbc:mysql://192.168.8.202:3306/dit_config?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: dcm
    password: N8xvZ2Q4kP5mT7wL
    driver-class-name: com.mysql.cj.jdbc.Driver

    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 60000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  cloud:
    nacos:
      discovery:
        server-addr: localhost:20001
        username: nacos
        password: nacos
        namespace: 60a9e1d6-a938-4cb7-966c-5e8482ae5612
      config:
        username: nacos
        password: nacos
        server-addr: localhost:20001
        namespace: 60a9e1d6-a938-4cb7-966c-5e8482ae5612

  config:
    import: nacos:dit-system.yaml

mybatis-flex:
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    root: INFO # 全局日志级别
    site.ahzx: DEBUG
    org.springframework: INFO      # Spring 框架日志
    com.mybatisflex: INFO           # MyBatis-Flex 日志
    org.apache.ibatis: INFO         # MyBatis 日志
