server:
  address: 0.0.0.0
  port: 8081

spring:
  application:
    name: dit-auth-service
  data:
    redis:
      host: localhost
      port: 16379
      password: 123456  # 如果没有密码可省略
      timeout: 5000

  cloud:
    nacos:
      discovery:
        server-addr: localhost:20001
        username: nacos
        password: nacos
        namespace: 60a9e1d6-a938-4cb7-966c-5e8482ae5612
      config:
        username: nacos
        password: nacos
        server-addr: localhost:20001
        namespace: 60a9e1d6-a938-4cb7-966c-5e8482ae5612

  config:
    import: nacos:dit-auth.yaml

jwt:
  secret: yuzhouwudichaojidashuaibihuxuefengshiye # 请替换为实际的JWT密钥
  expiration-seconds: 3600 # token有效期(秒)
  token-header: Authorization
  token-prefix: "Bearer "


